/* Chimie 3e-6e : cours spécifiques, 264 exercices, 120 flashcards et outils interactifs. */
(function () {
  if (typeof CESS_LIBRARY_DATA === 'undefined' || !CESS_LIBRARY_DATA.chimie) return;

  var TOPICS = [
    ['3e','Matière et mélanges','Une espèce chimique possède des propriétés propres. Un corps pur n’en contient qu’une ; un mélange en contient plusieurs.','Corps pur|une seule espèce chimique','Mélange homogène|constituants indiscernables à l’œil nu','Mélange hétérogène|plusieurs phases visibles','Séparation|filtration, décantation ou distillation selon les propriétés','ρ = m/V','Une masse de 200 g occupe 250 mL : ρ = 0,80 g/mL.','Séparer du sable et du sel : dissolution, filtration puis évaporation.','Une filtration ne sépare pas un soluté dissous.'],
    ['3e','Atomes et éléments','La matière est constituée d’atomes. Le noyau contient protons et neutrons ; les électrons occupent le nuage électronique.','Numéro atomique Z|nombre de protons','Nombre de masse A|protons plus neutrons','Isotope|même Z mais nombre de neutrons différent','Ion|atome ou groupe ayant gagné ou perdu des électrons','N = A − Z','Pour ²³₁₁Na : 11 protons, 12 neutrons et 11 électrons si l’atome est neutre.','Identifier un ion à partir de Z, A et de sa charge.','La charge d’un ion ne modifie jamais son nombre de protons.'],
    ['3e','Tableau périodique','Le tableau classe les éléments par numéro atomique croissant. Une ligne est une période et une colonne rassemble souvent des propriétés proches.','Période|ligne du tableau','Famille|colonne aux propriétés apparentées','Électron de valence|électron de la couche externe','Gaz noble|famille 18, couche externe stable','Z = nombre de protons','Le sodium Na est en période 3 et famille 1 : il forme souvent Na⁺.','Comparer la réactivité de métaux alcalins à partir d’observations.','La masse atomique ne détermine pas la place moderne : c’est Z.'],
    ['3e','Liaisons chimiques','Les atomes s’associent par transfert ou partage d’électrons. La structure explique les propriétés des substances.','Liaison covalente|partage d’une ou plusieurs paires d’électrons','Liaison ionique|attraction entre ions opposés','Molécule|assemblage neutre d’atomes liés','Réseau ionique|organisation répétée de cations et d’anions','charge totale = somme des charges','Ca²⁺ exige deux Cl⁻ : la formule électriquement neutre est CaCl₂.','Construire des modèles de H₂O, CO₂ et NaCl puis comparer.','NaCl solide n’est pas constitué de molécules NaCl isolées.'],
    ['3e','Réactions chimiques','Une réaction transforme des réactifs en produits tout en conservant les atomes et la charge totale.','Réactif|espèce consommée','Produit|espèce formée','Coefficient|nombre placé devant une formule','Équation équilibrée|même nombre de chaque atome des deux côtés','atomes avant = atomes après','2 H₂ + O₂ → 2 H₂O conserve 4 H et 2 O.','Faire réagir vinaigre et bicarbonate et identifier le dégagement gazeux.','On modifie les coefficients, jamais les indices des formules.'],
    ['3e','Quantité de matière','La mole permet de compter un très grand nombre d’entités. La masse molaire relie une quantité de matière à une masse mesurable.','Mole|6,022 × 10²³ entités','Masse molaire M|masse d’une mole en g/mol','Quantité n|nombre de moles','Constante d’Avogadro|Nₐ = 6,022 × 10²³ mol⁻¹','n = m/M ; N = nNₐ','9,0 g d’eau avec M = 18,0 g/mol correspondent à 0,50 mol.','Peser différentes quantités de NaCl et convertir en moles.','Toujours convertir la masse et garder des unités compatibles.'],
    ['4e','Stœchiométrie','Les coefficients d’une équation équilibrée donnent les proportions molaires. Le réactif limitant fixe la quantité maximale de produit.','Rapport molaire|rapport des coefficients stœchiométriques','Réactif limitant|réactif consommé en premier','Réactif en excès|réactif restant après réaction','Rendement|part du produit réellement obtenu','η = n obtenu / n théorique × 100 %','Avec 2 mol H₂ et 2 mol O₂, H₂ limite et forme au plus 2 mol H₂O.','Comparer les quantités avant et après une précipitation.','Ne jamais comparer directement des masses sans passer par les moles.'],
    ['4e','Solutions','Une solution est un mélange homogène. Sa concentration exprime la quantité de soluté par volume final de solution.','Solvant|constituant majoritaire qui dissout','Soluté|espèce dissoute','Concentration molaire|moles de soluté par litre de solution','Dilution|ajout de solvant sans changer la quantité de soluté','c = n/V ; C₁V₁ = C₂V₂','0,10 mol dans 0,25 L donne c = 0,40 mol/L.','Préparer 100 mL d’une solution par dissolution puis par dilution.','Le volume à utiliser est le volume final de solution.'],
    ['4e','Acides et bases','En solution aqueuse, un acide peut céder un proton et une base peut le capter. Le pH renseigne sur l’acidité.','Acide|donneur de proton H⁺','Base|accepteur de proton H⁺','Neutralisation|réaction entre acide et base','Indicateur|espèce dont la couleur dépend du pH','pH = −log[H₃O⁺]','[H₃O⁺] = 10⁻³ mol/L correspond à pH 3.','Établir une échelle de pH avec indicateur universel et solutions diluées.','Une solution dix fois plus acide perd une unité de pH, pas dix.'],
    ['4e','Oxydoréduction','Une oxydoréduction transfère des électrons. L’oxydant les capte et le réducteur les cède.','Oxydation|perte d’électrons','Réduction|gain d’électrons','Oxydant|espèce qui capte des électrons','Réducteur|espèce qui cède des électrons','électrons perdus = électrons gagnés','Zn → Zn²⁺ + 2e⁻ est une oxydation.','Plonger zinc et cuivre dans des solutions ioniques et observer les transformations.','Oxydant et espèce oxydée ne désignent pas la même chose.'],
    ['4e','Gaz','Le modèle du gaz parfait relie pression, volume, température absolue et quantité. Les particules sont en mouvement permanent.','Pression|effet des chocs sur les parois','Température absolue|mesure en kelvins','Volume molaire|volume occupé par une mole dans des conditions données','Gaz parfait|modèle de particules sans volume propre ni interaction','pV = nRT ; T(K) = θ(°C) + 273,15','À n et T constants, diviser V par deux double p.','Mesurer le volume d’un gaz produit et noter température et pression.','Jamais de degrés Celsius directement dans pV = nRT.'],
    ['4e','Chimie organique','La chimie organique étudie surtout les composés du carbone. Une formule et un groupe fonctionnel permettent de classer et nommer.','Hydrocarbure|composé de carbone et hydrogène uniquement','Alcane|hydrocarbure à liaisons simples','Alcène|hydrocarbure possédant C=C','Groupe fonctionnel|motif responsable de propriétés caractéristiques','alcane : CₙH₂ₙ₊₂','Le propane C₃H₈ est un alcane ; l’éthène C₂H₄ est un alcène.','Construire des isomères simples avec des modèles moléculaires.','Deux molécules de même formule brute peuvent avoir des structures différentes.'],
    ['5e','Structure électronique','La configuration électronique décrit la répartition des électrons. Elle explique la périodicité et la formation d’ions.','Orbitale|région où la présence de l’électron est probable','Sous-couche|ensemble d’orbitales de même type','Configuration|répartition des électrons dans les niveaux','Ion stable|espèce formée par gain ou perte d’électrons','capacité : s², p⁶','Na : 1s² 2s² 2p⁶ 3s¹ ; Na⁺ perd l’électron 3s.','Relier spectres de raies simplifiés et transitions électroniques.','Une orbitale n’est pas une trajectoire circulaire.'],
    ['5e','Thermochimie','La thermochimie étudie les transferts d’énergie associés aux transformations. Le signe de ΔH dépend du système choisi.','Exothermique|le système libère de l’énergie','Endothermique|le système reçoit de l’énergie','Enthalpie|fonction d’état utile à pression constante','Loi de Hess|ΔH dépend seulement des états initial et final','q = mcΔT ; ΔH < 0 si exothermique','100 g d’eau gagnent 5 °C : q = 100 × 4,18 × 5 = 2090 J.','Mesurer la variation de température lors d’une neutralisation.','Une hausse de température du milieu correspond souvent à un système exothermique.'],
    ['5e','Cinétique','La cinétique décrit la vitesse d’une réaction. Les collisions doivent être assez énergétiques et correctement orientées.','Vitesse|variation d’une quantité par unité de temps','Énergie d’activation|barrière énergétique minimale','Catalyseur|nouveau chemin plus rapide, régénéré','Collision efficace|collision conduisant à une transformation','v = −Δ[réactif]/Δt','Doubler la concentration augmente souvent la fréquence des collisions.','Comparer une réaction à deux températures en ne changeant qu’une variable.','Un catalyseur accélère l’équilibre mais ne change pas sa position.'],
    ['5e','Équilibre chimique','À l’équilibre, réactions directe et inverse continuent à même vitesse. Les concentrations deviennent constantes, non nécessairement égales.','Équilibre dynamique|vitesses directe et inverse égales','Quotient Q|rapport calculé à l’état étudié','Constante K|valeur de Q à l’équilibre','Le Châtelier|réponse du système à une perturbation','si Q < K, évolution dans le sens direct','Ajouter un réactif peut déplacer temporairement l’évolution vers les produits.','Observer un équilibre coloré après variation de concentration ou température.','À l’équilibre, la réaction ne s’est pas arrêtée.'],
    ['5e','Acides-bases approfondis','La force d’un acide dépend de son équilibre avec l’eau. Les couples conjugués diffèrent d’un proton.','Ka|constante d’acidité','pKa|−log Ka','Tampon|solution résistant à une faible variation de pH','Équivalence|proportions stœchiométriques au titrage','pH = pKa + log([base]/[acide])','Dans un tampon équimolaire, pH = pKa.','Réaliser un titrage pH-métrique et déterminer l’équivalence.','Équivalence et neutralité pH 7 ne sont pas toujours confondues.'],
    ['5e','Électrochimie','Une pile transforme une réaction spontanée en courant électrique. L’électrolyse force une réaction grâce à un générateur.','Anode|siège de l’oxydation','Cathode|siège de la réduction','Pile|générateur électrochimique spontané','Électrolyse|transformation non spontanée imposée','E°pile = E°cathode − E°anode','Dans une pile Zn/Cu, les électrons vont du zinc vers le cuivre.','Construire une pile simple et mesurer sa tension à vide.','Anode signifie toujours oxydation, même si son signe change.'],
    ['6e','Chimie organique','Les familles organiques se reconnaissent par leur groupe fonctionnel. Structure, polarité et interactions influencent les propriétés.','Alcool|groupe hydroxyle sur carbone saturé','Aldéhyde|groupe terminal –CHO','Cétone|groupe carbonyle interne','Acide carboxylique|groupe –COOH','ester : R–COO–R’','CH₃COOH est l’acide éthanoïque ; CH₃COOCH₂CH₃ est un ester.','Comparer solubilité et température d’ébullition de petites molécules.','Le groupe –OH d’un acide carboxylique ne suffit pas à le classer alcool.'],
    ['6e','Réactions organiques','Les transformations organiques se classent selon les liaisons rompues et formées. Les conditions opératoires orientent les produits.','Addition|fixation sur une liaison multiple','Substitution|remplacement d’un groupe','Élimination|formation d’une liaison multiple avec départ de groupes','Estérification|acide carboxylique plus alcool','acide + alcool ⇌ ester + eau','Éthène + H₂ donne éthane par addition.','Synthétiser un ester sous chauffage à reflux puis l’identifier par son odeur sans inhalation directe.','Un catalyseur accélère l’estérification mais ne modifie pas le rendement à l’équilibre.'],
    ['6e','Polymères et matériaux','Un polymère est une macromolécule issue de monomères. Sa structure conditionne rigidité, élasticité et recyclage.','Monomère|petite molécule répétée','Polymère|longue chaîne ou réseau','Thermoplastique|ramollit lorsqu’on chauffe','Thermodurcissable|réseau réticulé non refondable','degré n = masse molaire polymère / masse motif','Un polyéthylène de 28 000 g/mol contient environ 1000 motifs C₂H₄.','Comparer densité et comportement thermique de plastiques identifiés.','Le code de recyclage n’assure pas que l’objet sera effectivement recyclé.'],
    ['6e','Chimie et environnement','La chimie mesure les flux de matière, les polluants et les impacts. La chimie verte agit à la source du procédé.','Polluant|substance causant un effet nocif selon dose et exposition','Eutrophisation|excès nutritif et manque d’oxygène','Gaz à effet de serre|gaz absorbant une partie de l’infrarouge','Chimie verte|prévention des déchets et dangers','impact = danger × exposition','Une faible concentration peut rester problématique si l’exposition est durable.','Mesurer nitrates ou dureté d’eaux et discuter limites du protocole.','Naturel ne signifie pas automatiquement inoffensif.'],
    ['6e','Analyse chimique','Une analyse identifie ou dose une espèce. La qualité du résultat dépend de l’étalonnage, des incertitudes et du prélèvement.','Analyse qualitative|identifier une espèce','Analyse quantitative|déterminer une quantité','Étalonnage|relier signal et concentration','Incertitude|intervalle associé au résultat','à équivalence : proportions stœchiométriques','Une droite A = kc permet de retrouver c à partir d’une absorbance mesurée.','Construire une gamme étalon et analyser un échantillon inconnu.','Plus de chiffres affichés ne signifie pas plus de précision.'],
    ['6e','Atelier CESS : problèmes intégrés','Un problème intégré demande de sélectionner les données utiles, modéliser, calculer, critiquer puis communiquer une conclusion.','Modélisation|traduire la situation en relations chimiques','Donnée utile|information nécessaire à la résolution','Validation|contrôler unités, ordre de grandeur et cohérence','Conclusion|réponse justifiée liée à la question','résultat = valeur ± incertitude, avec unité','Pour un dosage, relier volume équivalent, concentration titrante et rapport molaire.','Concevoir un protocole de dosage puis identifier variables et incertitudes.','Une réponse numérique sans démarche, unité ni critique reste incomplète.']
  ];

  function esc(s){return String(s).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
  function pairs(row){return row.slice(3,7).map(function(x){var p=x.split('|');return {term:p[0],definition:p[1]};});}
  function course(row){
    var ps=pairs(row);
    return '<h4>Comprendre le phénomène</h4><p>'+esc(row[2])+'</p>'+
      '<div class="chem-flow"><span>Observer</span><b>→</b><span>Modéliser</span><b>→</b><span>Calculer</span><b>→</b><span>Vérifier</span></div>'+
      '<h4>Notions essentielles</h4><dl class="chem-defs">'+ps.map(function(p){return '<div><dt>'+esc(p.term)+'</dt><dd>'+esc(p.definition)+'</dd></div>';}).join('')+'</dl>'+
      '<h4>Formule et unités</h4><p class="chem-formula">'+esc(row[7])+'</p><p>Écris toujours les données avec leurs unités, convertis-les avant le calcul et arrondis seulement à la fin.</p>'+
      '<h4>Exemple résolu</h4><p>'+esc(row[8])+'</p><ol><li>Repérer la grandeur cherchée.</li><li>Choisir la relation adaptée.</li><li>Remplacer avec des unités compatibles.</li><li>Contrôler l’ordre de grandeur.</li></ol>'+
      '<h4>Laboratoire et sécurité</h4><p>'+esc(row[9])+'</p><p><strong>Sécurité :</strong> lunettes fermées, blouse, cheveux attachés, lecture des pictogrammes et déchets déposés dans le récipient prévu. Ne jamais goûter ni pipeter à la bouche.</p>'+
      '<h4>Erreur fréquente</h4><p class="chem-warning">'+esc(row[10])+'</p>'+
      '<h4>Synthèse CESS</h4><p>Je sais définir les notions, expliquer le modèle, appliquer la relation, interpréter une expérience et justifier une conclusion avec une unité et une phrase complète.</p>';
  }
  function exercises(row,index,allPairs){
    var ps=pairs(row), levels=['Mémoriser','Comprendre','Appliquer','Analyser'];
    var out=ps.map(function(p,i){
      var wrong=allPairs.filter(function(x){return x.term!==p.term;}).slice(index+i,index+i+3);
      if(wrong.length<3)wrong=allPairs.slice(0,3);
      var opts=[p.definition].concat(wrong.map(function(x){return x.definition;}));
      var rotated=opts.slice(i%4).concat(opts.slice(0,i%4)),correct=rotated.indexOf(p.definition);
      return {question:'Quelle définition correspond à « '+p.term+' » ?',options:rotated,correct:correct,correction:p.term+' : '+p.definition+'.',niveau:levels[i],contentVersion:3};
    });
    ps.forEach(function(p,i){
      var distract=allPairs.filter(function(x){return ps.every(function(y){return y.term!==x.term;});})[(index*3+i)%allPairs.length];
      out.push({question:'Quelle notion appartient directement au chapitre « '+row[1]+' » ?',options:[distract.term,p.term,'Aucune de ces notions','Toutes sans distinction'],correct:1,correction:p.term+' est bien une notion centrale de ce chapitre : '+p.definition+'.',niveau:'Comprendre',contentVersion:3});
    });
    out.push({question:'Quelle relation ou règle faut-il mobiliser en priorité dans ce chapitre ?',options:['Aucune relation ne peut être vérifiée',row[7],'Toujours multiplier toutes les données','Utiliser les degrés Celsius dans toutes les formules'],correct:1,correction:'La relation de référence est : '+row[7]+'. Il faut aussi vérifier les unités et le domaine de validité.',niveau:'Appliquer',contentVersion:3});
    out.push({question:'Quelle activité permet le mieux de vérifier expérimentalement ce chapitre ?',options:['Mémoriser sans observer','Changer toutes les variables à la fois',row[9],'Ignorer les incertitudes'],correct:2,correction:'Une expérience utile contrôle les variables, mesure une grandeur et explicite ses limites : '+row[9],niveau:'Analyser',contentVersion:3});
    out.push({question:'Quelle erreur faut-il éviter ?',options:['Donner une unité et vérifier le résultat',row[10],'Expliquer le modèle utilisé','Comparer le résultat à un ordre de grandeur'],correct:1,correction:'Erreur à éviter : '+row[10],niveau:'Analyser',contentVersion:3});
    return out;
  }
  var allPairs=TOPICS.reduce(function(a,r){return a.concat(pairs(r));},[]);
  TOPICS.forEach(function(row,index){
    var chapters=CESS_LIBRARY_DATA.chimie.data[row[0]]||[];
    var ch=chapters.find(function(c){return c.titre.replace(/^\d+\.\s*/,'')===row[1];});
    if(!ch)return;
    ch.desc=row[2]; ch.cours=course(row); ch.exercices=exercises(row,index,allPairs);
    ch.objectifs=['Expliquer les notions et le modèle de « '+row[1]+' »','Résoudre un exercice de « '+row[1]+' » avec unités','Analyser une expérience liée à « '+row[1]+' » et ses limites'];
    ch.fiches=pairs(row).concat([{term:'Relation clé',definition:row[7],example:row[8]}]).map(function(f){return {term:f.term,definition:f.definition,example:f.example||row[8]};});
    ch.contentVersion=3;
  });

  var ELEMENTS = [
    'H|Hydrogène|1.008|1|1','He|Hélium|4.003|18|1','Li|Lithium|6.94|1|2','Be|Béryllium|9.012|2|2','B|Bore|10.81|13|2','C|Carbone|12.011|14|2','N|Azote|14.007|15|2','O|Oxygène|15.999|16|2','F|Fluor|18.998|17|2','Ne|Néon|20.180|18|2',
    'Na|Sodium|22.990|1|3','Mg|Magnésium|24.305|2|3','Al|Aluminium|26.982|13|3','Si|Silicium|28.085|14|3','P|Phosphore|30.974|15|3','S|Soufre|32.06|16|3','Cl|Chlore|35.45|17|3','Ar|Argon|39.948|18|3',
    'K|Potassium|39.098|1|4','Ca|Calcium|40.078|2|4','Sc|Scandium|44.956|3|4','Ti|Titane|47.867|4|4','V|Vanadium|50.942|5|4','Cr|Chrome|52.00|6|4','Mn|Manganèse|54.938|7|4','Fe|Fer|55.845|8|4','Co|Cobalt|58.933|9|4','Ni|Nickel|58.693|10|4','Cu|Cuivre|63.546|11|4','Zn|Zinc|65.38|12|4','Ga|Gallium|69.723|13|4','Ge|Germanium|72.630|14|4','As|Arsenic|74.922|15|4','Se|Sélénium|78.971|16|4','Br|Brome|79.904|17|4','Kr|Krypton|83.798|18|4',
    'Rb|Rubidium|85.468|1|5','Sr|Strontium|87.62|2|5','Y|Yttrium|88.906|3|5','Zr|Zirconium|91.224|4|5','Nb|Niobium|92.906|5|5','Mo|Molybdène|95.95|6|5','Tc|Technétium|98|7|5','Ru|Ruthénium|101.07|8|5','Rh|Rhodium|102.906|9|5','Pd|Palladium|106.42|10|5','Ag|Argent|107.868|11|5','Cd|Cadmium|112.414|12|5','In|Indium|114.818|13|5','Sn|Étain|118.710|14|5','Sb|Antimoine|121.760|15|5','Te|Tellure|127.60|16|5','I|Iode|126.904|17|5','Xe|Xénon|131.293|18|5',
    'Cs|Césium|132.905|1|6','Ba|Baryum|137.327|2|6','La|Lanthane|138.905|3|8','Ce|Cérium|140.116|4|8','Pr|Praséodyme|140.908|5|8','Nd|Néodyme|144.242|6|8','Pm|Prométhium|145|7|8','Sm|Samarium|150.36|8|8','Eu|Europium|151.964|9|8','Gd|Gadolinium|157.25|10|8','Tb|Terbium|158.925|11|8','Dy|Dysprosium|162.500|12|8','Ho|Holmium|164.930|13|8','Er|Erbium|167.259|14|8','Tm|Thulium|168.934|15|8','Yb|Ytterbium|173.045|16|8','Lu|Lutécium|174.967|17|8',
    'Hf|Hafnium|178.49|4|6','Ta|Tantale|180.948|5|6','W|Tungstène|183.84|6|6','Re|Rhénium|186.207|7|6','Os|Osmium|190.23|8|6','Ir|Iridium|192.217|9|6','Pt|Platine|195.084|10|6','Au|Or|196.967|11|6','Hg|Mercure|200.592|12|6','Tl|Thallium|204.38|13|6','Pb|Plomb|207.2|14|6','Bi|Bismuth|208.980|15|6','Po|Polonium|209|16|6','At|Astate|210|17|6','Rn|Radon|222|18|6',
    'Fr|Francium|223|1|7','Ra|Radium|226|2|7','Ac|Actinium|227|3|9','Th|Thorium|232.038|4|9','Pa|Protactinium|231.036|5|9','U|Uranium|238.029|6|9','Np|Neptunium|237|7|9','Pu|Plutonium|244|8|9','Am|Américium|243|9|9','Cm|Curium|247|10|9','Bk|Berkélium|247|11|9','Cf|Californium|251|12|9','Es|Einsteinium|252|13|9','Fm|Fermium|257|14|9','Md|Mendélévium|258|15|9','No|Nobélium|259|16|9','Lr|Lawrencium|266|17|9',
    'Rf|Rutherfordium|267|4|7','Db|Dubnium|268|5|7','Sg|Seaborgium|269|6|7','Bh|Bohrium|270|7|7','Hs|Hassium|269|8|7','Mt|Meitnérium|278|9|7','Ds|Darmstadtium|281|10|7','Rg|Roentgenium|282|11|7','Cn|Copernicium|285|12|7','Nh|Nihonium|286|13|7','Fl|Flérovium|289|14|7','Mc|Moscovium|290|15|7','Lv|Livermorium|293|16|7','Ts|Tennessine|294|17|7','Og|Oganesson|294|18|7'
  ].map(function(s,i){var p=s.split('|');return {z:i+1,s:p[0],n:p[1],m:p[2],g:+p[3],p:+p[4]};});
  window.CHEM_ELEMENTS=ELEMENTS;
  function family(e){
    if(e.p===8)return 'lanthanide'; if(e.p===9)return 'actinide';
    if(e.g===18)return 'noble'; if(e.g===17)return 'halogene'; if(e.g===1&&e.z!==1)return 'alcalin';
    if(e.g===2)return 'alcalino'; if(e.g>=3&&e.g<=12)return 'transition';
    if([5,14,32,33,51,52,84].indexOf(e.z)>=0)return 'metalloide';
    if([1,6,7,8,15,16,34].indexOf(e.z)>=0)return 'nonmetal'; return 'metal';
  }
  ELEMENTS.forEach(function(e){e.f=family(e);});
  var familyLabels={alcalin:'Métal alcalin',alcalino:'Alcalino-terreux',transition:'Métal de transition',metal:'Autre métal',metalloide:'Métalloïde',nonmetal:'Non-métal',halogene:'Halogène',noble:'Gaz noble',lanthanide:'Lanthanide',actinide:'Actinide'};
  window.renderPeriodicTable=function(){
    var q=(document.getElementById('chemElementSearch')||{}).value||'',f=(document.getElementById('chemFamilyFilter')||{}).value||'all';
    q=q.toLowerCase();
    var html=ELEMENTS.map(function(e){
      var show=(!q||e.s.toLowerCase().indexOf(q)>=0||e.n.toLowerCase().indexOf(q)>=0||String(e.z)===q)&&(f==='all'||e.f===f);
      return '<button class="chem-element '+e.f+(show?'':' filtered')+'" style="--col:'+e.g+';--row:'+e.p+'" onclick="showElement('+e.z+')" aria-label="'+esc(e.n)+', numéro atomique '+e.z+'"><small>'+e.z+'</small><strong>'+e.s+'</strong><span>'+esc(e.n)+'</span></button>';
    }).join('');
    var grid=document.getElementById('periodicGrid'); if(grid)grid.innerHTML=html;
  };
  window.showElement=function(z){
    var e=ELEMENTS[z-1],electrons=e.z,approxA=Math.round(parseFloat(e.m)),approxNeutrons=Math.max(0,approxA-e.z);
    document.getElementById('elementDetail').innerHTML='<button class="chem-close" type="button" onclick="closeElementDetail()" aria-label="Fermer la fiche">×</button><span class="chem-big-symbol">'+e.s+'</span><div><h3>'+esc(e.n)+'</h3><p><strong>Z = '+e.z+'</strong> · masse atomique moyenne ≈ '+e.m+' u</p><p>'+familyLabels[e.f]+' · période '+(e.p>7?(e.p===8?'lanthanides':'actinides'):e.p)+' · groupe '+e.g+'</p><p>Atome neutre : '+e.z+' protons et '+electrons+' électrons. Le nombre de neutrons dépend de l’isotope.</p><p><small>Estimation pédagogique : avec A ≈ '+approxA+', on obtient environ '+approxNeutrons+' neutrons (A − Z). Cette valeur arrondie ne décrit pas tous les isotopes.</small></p></div>';
  };
  window.closeElementDetail=function(){document.getElementById('elementDetail').innerHTML='';};
  function chaptersHtml(p){
    return ['3e','4e','5e','6e'].map(function(year){var chapters=allChaps('chimie').filter(function(c){return c.annee===year;});return '<details class="memo-group"'+(p.year===year?' open':'')+'><summary><strong>'+year+' secondaire</strong><span>'+chapters.length+' chapitres · '+chapters.reduce(function(n,c){return n+c.exercices.length;},0)+' exercices</span></summary><div class="content-grid">'+chapters.map(chapterLink).join('')+'</div></details>';}).join('');
  }
  window.renderChemistryHub=function(root,p){
    root.innerHTML='<div class="page-header chem-header"><div><span class="eyebrow">CHIMIE · 3e À 6e</span><h1>⚗️ Comprendre la matière</h1><p>24 cours structurés, 264 exercices corrigés, 120 flashcards et des outils interactifs.</p></div><button class="button secondary" onclick="renderLibrary()">← Catalogue</button></div>'+
      '<section class="chem-tools"><div><span class="eyebrow">OUTIL INTERACTIF</span><h2>Tableau périodique</h2><p>Recherche un élément ou filtre une famille, puis touche une case pour afficher sa fiche.</p></div><div class="chem-filters"><label>Rechercher<input id="chemElementSearch" type="search" placeholder="O, oxygène ou 8" oninput="renderPeriodicTable()"></label><label>Famille<select id="chemFamilyFilter" onchange="renderPeriodicTable()"><option value="all">Toutes</option>'+Object.keys(familyLabels).map(function(k){return '<option value="'+k+'">'+familyLabels[k]+'</option>';}).join('')+'</select></label></div><div id="elementDetail" class="element-detail" aria-live="polite"></div><div class="periodic-wrap"><div id="periodicGrid" class="periodic-grid"></div></div><div class="chem-legend">'+Object.keys(familyLabels).map(function(k){return '<span class="'+k+'">'+familyLabels[k]+'</span>';}).join('')+'</div></section>'+
      '<section class="chem-quick-games"><h2>Entraînements rapides</h2><div class="game-grid"><button class="game-card" onclick="startChemistryGame(\'element\')"><span>⚛️</span><strong>Quel élément ?</strong><small>Symboles, noms et numéros atomiques</small></button><button class="game-card" onclick="startChemistryGame(\'family\')"><span>🧪</span><strong>Familles chimiques</strong><small>Replace les éléments dans leur famille</small></button><button class="game-card" onclick="startQuiz(\'chimie\')"><span>🎯</span><strong>Série mixte chimie</strong><small>Questions de tous les chapitres</small></button></div></section>'+chaptersHtml(p);
    renderPeriodicTable();
  };
  window.startChemistryGame=function(mode){
    showView('games');
    var pool=ELEMENTS.filter(function(e){return e.z<=54;});
    var cards=shuffle(pool).slice(0,10).map(function(e){
      var others=shuffle(pool.filter(function(x){return x.z!==e.z;})).slice(0,3);
      if(mode==='family')return {q:'À quelle famille appartient '+e.n+' ('+e.s+') ?',answer:familyLabels[e.f],opts:shuffle([familyLabels[e.f]].concat(others.map(function(x){return familyLabels[x.f];}))).filter(function(x,i,a){return a.indexOf(x)===i;})};
      return {q:'Quel élément possède le symbole '+e.s+' ?',answer:e.n,opts:shuffle([e.n].concat(others.map(function(x){return x.n;})))};
    });
    window.chemGame={cards:cards,index:0,score:0,mode:mode,saved:false}; renderChemistryGame();
  };
  window.renderChemistryGame=function(){
    var s=window.chemGame,p=document.getElementById('gamePanel'),c=s.cards[s.index];
    if(!c){if(!s.saved){s.saved=true;var pct=Math.round(s.score/s.cards.length*100);cessState.results.push({contentVersion:2,date:new Date().toISOString(),mode:s.mode==='family'?'Familles chimiques':'Tableau périodique',score:s.score,total:s.cards.length,percentage:pct,subject:'chimie'});cessSave();}p.innerHTML=(typeof rewardBanner==='function'?rewardBanner(s.score,s.cards.length):'')+'<div class="quiz-result"><h2>'+s.score+' / '+s.cards.length+'</h2><p>Série de chimie enregistrée dans ta progression.</p><button class="button primary" onclick="startChemistryGame(\''+s.mode+'\')">Rejouer</button> <button class="button secondary" onclick="renderGamePanel()">Tous les jeux</button></div>';return;}
    p.innerHTML='<button class="button secondary" onclick="renderGamePanel()">← Jeux</button><h2>Défi tableau périodique</h2><p>Question '+(s.index+1)+' / '+s.cards.length+'</p><h3>'+esc(c.q)+'</h3><div class="quiz-options">'+c.opts.map(function(o){return '<button class="quiz-option" data-answer="'+esc(o)+'" onclick="answerChemistryGame(this,this.dataset.answer)">'+esc(o)+'</button>';}).join('')+'</div><div id="chemGameFeedback"></div>';
  };
  window.answerChemistryGame=function(btn,value){
    var s=window.chemGame,c=s.cards[s.index],good=value===c.answer;
    if(good)s.score++; document.querySelectorAll('#gamePanel .quiz-option').forEach(function(b){b.disabled=true;if(b.textContent===c.answer)b.classList.add('correct');});if(!good)btn.classList.add('wrong');
    document.getElementById('chemGameFeedback').innerHTML='<p class="'+(good?'feedback-success':'feedback-retry')+'">'+(good?'✓ Bonne réponse !':'↺ La réponse était '+esc(c.answer)+'.')+'</p><button class="button primary" onclick="chemGame.index++;renderChemistryGame()">Continuer →</button>';
  };
})();
