/* Physique 3e-6e : 24 cours spécifiques, 240 exercices et 120 flashcards. */
(function(){
if(typeof CESS_LIBRARY_DATA==='undefined'||!CESS_LIBRARY_DATA.physique)return;
var T=[
['3e','Mesures et démarche expérimentale','Une mesure associe une valeur, une unité et une incertitude. Un protocole fiable ne modifie qu’un facteur à la fois.','Unité SI|référence internationale pour exprimer une grandeur','Incertitude|intervalle raisonnable autour d’une mesure','Variable contrôlée|facteur maintenu constant','Proportionnalité|relation dont le graphique est une droite passant par l’origine','écart relatif = |mesure − référence| / référence × 100 %','2,50 km = 2500 m ; les chiffres significatifs traduisent la précision disponible.','Mesurer dix fois une durée et comparer moyenne et dispersion.','Une calculatrice donnant huit chiffres ne rend pas la mesure huit fois plus précise.'],
['3e','Cinématique','La cinématique décrit le mouvement sans en rechercher la cause. Le référentiel et l’intervalle de temps doivent être précisés.','Position|lieu occupé dans un référentiel','Trajectoire|ensemble des positions successives','Vitesse moyenne|distance parcourue divisée par la durée','Accélération|variation du vecteur vitesse par unité de temps','v = Δx/Δt ; a = Δv/Δt','150 m en 30 s donnent 5,0 m/s, soit 18 km/h.','Filmer un mouvement rectiligne et relever la position à intervalles réguliers.','Une vitesse moyenne ne décrit pas nécessairement la vitesse à chaque instant.'],
['3e','Forces','Une force modélise une interaction et se représente par un vecteur. Un objet au repos peut subir plusieurs forces qui se compensent.','Force|action modifiant le mouvement ou déformant','Poids|force gravitationnelle exercée par l’astre','Réaction normale|force de contact perpendiculaire au support','Équilibre|résultante des forces nulle','P = mg ; ΣF = 0 à l’équilibre','Une masse de 2,0 kg pèse environ 19,6 N sur Terre.','Établir le diagramme des forces d’un objet posé puis suspendu.','Masse en kilogrammes et poids en newtons ne sont pas la même grandeur.'],
['3e','Pression et fluides','La pression mesure la répartition d’une force sur une surface. Dans un fluide, elle agit dans toutes les directions.','Pression|force normale par unité de surface','Masse volumique|masse par unité de volume','Poussée d’Archimède|force verticale due au fluide déplacé','Flottabilité|équilibre entre poids et poussée','p = F/S ; ρ = m/V ; Fₐ = ρfluide gVdéplacé','100 N sur 0,020 m² donnent 5000 Pa.','Comparer l’enfoncement produit par une même force sur deux surfaces.','Une grande force ne signifie pas toujours une grande pression : la surface compte.'],
['3e','Énergie','L’énergie caractérise la capacité d’un système à produire une transformation. Elle se transfère et se convertit sans être créée.','Travail|transfert d’énergie par une force','Énergie cinétique|énergie associée au mouvement','Énergie potentielle|énergie liée à une position','Puissance|énergie transférée par unité de temps','Ec = mv²/2 ; Ep = mgh ; P = E/Δt','Doubler la vitesse multiplie l’énergie cinétique par quatre.','Mesurer la hauteur atteinte après le mouvement d’un chariot sur une pente.','La conservation de l’énergie n’implique pas la conservation de l’énergie mécanique avec frottements.'],
['3e','Chaleur et température','La température décrit l’état thermique ; la chaleur est un transfert d’énergie dû à une différence de température.','Température|grandeur liée à l’agitation microscopique','Chaleur|énergie transférée thermiquement','Capacité thermique|énergie nécessaire pour élever la température','Changement d’état|transformation physique à température caractéristique','Q = mcΔT','Chauffer 1,0 kg d’eau de 1 °C demande environ 4180 J.','Comparer le chauffage de masses égales d’eau et d’huile.','Chaleur et température ne sont pas des synonymes.'],
['4e','Électricité continue','Le courant correspond à un déplacement ordonné de charges. Tension, intensité et résistance décrivent le fonctionnement d’un circuit.','Intensité|débit de charge électrique','Tension|énergie transférée par unité de charge','Résistance|opposition au passage du courant','Conducteur ohmique|dipôle vérifiant U proportionnel à I','I = Q/Δt ; U = RI','Une résistance de 6 Ω parcourue par 2 A a une tension de 12 V.','Tracer la caractéristique U(I) d’une résistance avec voltmètre et ampèremètre.','Un ampèremètre se branche en série et un voltmètre en dérivation.'],
['4e','Circuits électriques','Les lois des nœuds et des mailles expriment la conservation de la charge et de l’énergie dans un circuit.','Série|dipôles traversés par la même intensité','Parallèle|dipôles soumis à la même tension','Nœud|point où plusieurs branches se rejoignent','Puissance électrique|énergie transférée par seconde','P = UI ; série : Réq = R₁ + R₂','Deux résistances de 2 Ω et 3 Ω en série donnent 5 Ω.','Comparer courant et tension dans des montages série et parallèle.','Ne jamais mesurer une résistance dans un circuit sous tension.'],
['4e','Magnétisme','Un champ magnétique décrit l’action des aimants et des courants dans l’espace. Il possède direction et sens.','Champ magnétique|grandeur vectorielle notée B','Ligne de champ|courbe tangente au champ','Électroaimant|bobine produisant un champ avec un courant','Pôle magnétique|zone d’interaction forte d’un aimant','B augmente avec I dans une bobine donnée','Une boussole s’aligne localement avec le champ magnétique.','Cartographier le champ d’un aimant avec plusieurs boussoles.','Les lignes de champ sont un modèle, pas des fils matériels.'],
['4e','Ondes','Une onde transporte de l’énergie et de l’information sans transport global de matière. Sa fréquence est imposée par la source.','Période|durée d’un cycle','Fréquence|nombre de cycles par seconde','Longueur d’onde|distance parcourue pendant une période','Célérité|vitesse de propagation de l’onde','f = 1/T ; v = λf','T = 0,020 s correspond à f = 50 Hz.','Créer des impulsions sur une corde et mesurer leur célérité.','Lorsqu’une onde change de milieu, sa fréquence reste celle de la source.'],
['4e','Son','Le son est une onde mécanique. La fréquence détermine principalement la hauteur et l’amplitude est liée à l’intensité.','Hauteur|caractère grave ou aigu lié à la fréquence','Intensité sonore|puissance reçue par unité de surface','Résonance|forte réponse près d’une fréquence propre','Timbre|composition en harmoniques','niveau L = 10 log(I/I₀)','Deux sons de même hauteur peuvent avoir des timbres différents.','Observer le signal d’un diapason puis d’une voix avec un microphone.','Les décibels utilisent une échelle logarithmique, pas linéaire.'],
['4e','Optique géométrique','L’optique géométrique modélise la lumière par des rayons. Réflexion, réfraction et lentilles expliquent de nombreuses images.','Réflexion|renvoi de la lumière par une surface','Réfraction|changement de direction lors d’un changement de milieu','Lentille convergente|lentille rassemblant des rayons parallèles','Image réelle|image projetable sur un écran','i = r ; n₁ sin i = n₂ sin r','Un rayon incident à 30° de la normale est réfléchi à 30°.','Mesurer la distance focale d’une lentille en formant une image nette.','Les angles optiques se mesurent par rapport à la normale.'],
['5e','Cinématique vectorielle','La position, la vitesse et l’accélération sont vectorielles. Leur direction compte autant que leur valeur.','Vecteur position|position par rapport à l’origine','Vecteur vitesse|tangent à la trajectoire','Vecteur accélération|variation du vecteur vitesse','Chute libre|mouvement soumis uniquement au poids','v = v₀ + at ; x = x₀ + v₀t + at²/2','Après 2,0 s de chute sans vitesse initiale, v ≈ 19,6 m/s vers le bas.','Analyser image par image la trajectoire d’un projectile.','Un mouvement circulaire uniforme possède une accélération non nulle.'],
['5e','Dynamique de Newton','Les lois de Newton relient interactions et évolution du mouvement dans un référentiel inertiel.','Inertie|conservation de la vitesse si la résultante est nulle','Résultante|somme vectorielle des forces','Action-réaction|forces opposées exercées sur deux corps différents','Système|objet ou ensemble choisi pour l’étude','ΣF = ma','6 N sur 2 kg produisent 3 m/s².','Étudier l’accélération d’un chariot pour plusieurs forces puis plusieurs masses.','Les forces d’action-réaction ne se compensent pas sur le même système.'],
['5e','Quantité de mouvement','La quantité de mouvement se conserve pour un système isolé et permet d’analyser chocs et recul.','Quantité de mouvement|vecteur p = mv','Impulsion|effet d’une force pendant une durée','Collision élastique|énergie cinétique aussi conservée','Centre de masse|point moyen pondéré par les masses','p = mv ; Δp = FmoyΔt','À même quantité de mouvement, doubler la masse divise la vitesse par deux.','Analyser une collision de chariots avec une vidéo.','La quantité de mouvement est vectorielle : les signes et directions comptent.'],
['5e','Gravitation','Toute masse crée un champ gravitationnel. Une orbite résulte d’une chute permanente autour d’un astre.','Gravitation|interaction attractive entre masses','Champ g|force gravitationnelle par unité de masse','Orbite|trajectoire sous l’effet de la gravitation','Satellite|objet en orbite autour d’un astre','F = Gm₁m₂/r² ; g = GM/r²','Doubler la distance divise la force gravitationnelle par quatre.','Modéliser une orbite avec une simulation et varier la vitesse initiale.','L’absence de poids apparent en orbite n’est pas une absence de gravité.'],
['5e','Énergie mécanique','Le travail de la résultante modifie l’énergie cinétique. Sans dissipation, l’énergie mécanique se conserve.','Énergie mécanique|somme de l’énergie cinétique et potentielle','Force conservative|travail indépendant du chemin','Rendement|énergie utile divisée par énergie reçue','Dissipation|conversion en énergie interne','ΔEc = ΣW ; Em = Ec + Ep','Une chute de hauteur h transforme mgh en énergie cinétique sans frottement.','Comparer énergie avant et après le mouvement d’un pendule réel.','Une énergie perdue mécaniquement est transformée, pas détruite.'],
['5e','Électrostatique','Les charges créent un champ électrique. Le potentiel permet de décrire l’énergie électrique par unité de charge.','Charge|propriété à l’origine de l’interaction électrique','Champ électrique|force par unité de charge positive','Potentiel|énergie potentielle par unité de charge','Condensateur|dispositif stockant charges et énergie','F = k|q₁q₂|/r² ; E = F/q','Deux charges de même signe se repoussent.','Électriser des objets par frottement et tester attraction et répulsion.','Un objet neutre peut être attiré par polarisation.'],
['6e','Électromagnétisme','Un champ magnétique agit sur des charges mobiles. Une variation de flux magnétique peut produire une tension induite.','Force magnétique|force perpendiculaire à v et B','Flux magnétique|mesure du champ traversant une surface','Induction|apparition d’une tension par variation de flux','Transformateur|dispositif modifiant une tension alternative','F = |q|vB sinθ ; e = −ΔΦ/Δt','Une charge parallèle au champ subit une force magnétique nulle.','Déplacer un aimant dans une bobine et observer la tension induite.','La loi de Lenz s’oppose à la variation du flux, pas au flux lui-même.'],
['6e','Oscillations','Un oscillateur échange périodiquement différentes formes d’énergie. Le modèle harmonique conduit à une évolution sinusoïdale.','Équilibre stable|position vers laquelle agit la force de rappel','Amplitude|écart maximal à l’équilibre','Période propre|durée naturelle d’une oscillation','Résonance|amplitude forte lorsque l’excitation approche la fréquence propre','ressort : T = 2π√(m/k)','Multiplier la masse par quatre double la période d’un ressort idéal.','Mesurer la période d’un pendule pour plusieurs longueurs.','Pour de grandes amplitudes, la formule simple du pendule devient moins précise.'],
['6e','Ondes avancées','Le principe de superposition explique interférences, diffraction et ondes stationnaires.','Superposition|addition locale des perturbations','Interférence constructive|ondes en phase qui se renforcent','Interférence destructive|ondes en opposition qui se compensent','Onde stationnaire|motif avec nœuds et ventres fixes','corde : L = nλ/2','Une corde fixée aux deux extrémités contient un nombre entier de demi-longueurs d’onde.','Créer des ondes stationnaires sur une corde tendue.','Deux ondes peuvent se traverser sans se détruire définitivement.'],
['6e','Optique ondulatoire','La diffraction et les interférences révèlent le caractère ondulatoire de la lumière. Un spectre renseigne sur la source.','Diffraction|étalement par une ouverture ou un obstacle','Frange|zone claire ou sombre d’interférence','Spectre|répartition de l’intensité selon la longueur d’onde','Polarisation|sélection d’une direction de vibration','θ ≈ λ/a pour une fente étroite','Réduire la largeur de fente augmente l’étalement.','Observer la diffraction d’un laser en respectant les règles de sécurité.','Ne jamais regarder directement un faisceau laser ni sa réflexion spéculaire.'],
['6e','Physique moderne','Les modèles quantiques et nucléaires décrivent des phénomènes que la physique classique n’explique pas complètement.','Photon|quantum de rayonnement électromagnétique','Effet photoélectrique|émission d’électrons au-dessus d’une fréquence seuil','Radioactivité|transformation spontanée d’un noyau instable','Fission|division d’un noyau lourd','E = hf ; N = N₀(1/2)^(t/T½)','Doubler la fréquence double l’énergie d’un photon.','Exploiter une courbe de décroissance et déterminer une demi-vie.','L’intensité lumineuse augmente le nombre de photons, pas l’énergie de chacun.'],
['6e','Atelier CESS : résolution intégrée','Résoudre un problème demande de modéliser, sélectionner les lois, calculer puis critiquer le résultat.','Modélisation|simplification raisonnée de la situation','Analyse dimensionnelle|contrôle des dimensions d’une relation','Ordre de grandeur|estimation de la taille plausible du résultat','Incertitude|limite quantitative de la mesure','résultat = valeur ± incertitude, avec unité','Dans d = vt, m/s multiplié par s donne bien m.','Concevoir un protocole, identifier variables, répétitions et incertitudes.','Une relation dimensionnellement correcte peut néanmoins être physiquement fausse.']
];
function safe(s){return String(s||'').replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
function pairs(r){return r.slice(3,7).map(function(x){var p=x.split('|');return{term:p[0],definition:p[1]};});}
var all=T.reduce(function(a,r){return a.concat(pairs(r));},[]);
function course(r){var p=pairs(r);return'<h4>Modèle physique</h4><p>'+safe(r[2])+'</p><h4>Notions essentielles</h4><dl class="chem-defs">'+p.map(function(x){return'<div><dt>'+safe(x.term)+'</dt><dd>'+safe(x.definition)+'</dd></div>';}).join('')+'</dl><h4>Relation et unités</h4><p class="chem-formula">'+safe(r[7])+'</p><p>Avant tout calcul : choisir le système et le référentiel, écrire les données en unités SI puis vérifier les dimensions.</p><h4>Exemple résolu</h4><p>'+safe(r[8])+'</p><h4>Expérience</h4><p>'+safe(r[9])+'</p><p><strong>Sécurité :</strong> identifier les risques, protéger les yeux, couper l’alimentation avant de modifier un circuit et ne jamais utiliser un laser vers les yeux.</p><h4>Erreur fréquente</h4><p class="chem-warning">'+safe(r[10])+'</p><h4>Méthode CESS</h4><ol><li>Extraire les données et la grandeur cherchée.</li><li>Faire un schéma ou un diagramme.</li><li>Choisir la loi et justifier ses conditions.</li><li>Calculer avec unités.</li><li>Interpréter et critiquer le résultat.</li></ol>';}
function exercises(r,k){var p=pairs(r),out=[];p.forEach(function(x,i){var w=all[(k*5+i+7)%all.length],opts=[x.definition,w.definition,'Une unité sans grandeur','Une valeur sans modèle'];opts=opts.slice(i).concat(opts.slice(0,i));out.push({question:'Quelle définition correspond à « '+x.term+' » ?',options:opts,correct:opts.indexOf(x.definition),correction:x.term+' : '+x.definition+'.',niveau:i<2?'Mémoriser':'Comprendre',contentVersion:5});});p.forEach(function(x,i){var w=all[(k*4+i+17)%all.length];out.push({question:'Quelle notion appartient au chapitre « '+r[1]+' » ?',options:[w.term,x.term,'Aucune','Toutes sans distinction'],correct:1,correction:x.term+' appartient à ce chapitre : '+x.definition+'.',niveau:'Comprendre',contentVersion:5});});out.push({question:'Quelle relation faut-il connaître pour ce chapitre ?',options:['Toujours additionner toutes les données',r[7],'Aucune unité n’est nécessaire','Le résultat ne doit jamais être vérifié'],correct:1,correction:'Relation de référence : '+r[7]+'.',niveau:'Appliquer',contentVersion:5});out.push({question:'Quelle erreur faut-il éviter ?',options:['Faire un schéma','Vérifier les unités',r[10],'Donner une conclusion'],correct:2,correction:'Erreur à éviter : '+r[10],niveau:'Analyser',contentVersion:5});return out;}
T.forEach(function(r,k){var ch=(CESS_LIBRARY_DATA.physique.data[r[0]]||[]).find(function(c){return c.titre.replace(/^\d+\.\s*/,'')===r[1];});if(!ch)return;ch.desc=r[2];ch.cours=course(r);ch.exercices=exercises(r,k);ch.objectifs=['Expliquer le modèle de « '+r[1]+' »','Appliquer les relations avec les unités SI','Analyser une expérience et critiquer le résultat'];ch.fiches=pairs(r).concat([{term:'Relation clé',definition:r[7]}]).map(function(f){return{term:f.term,definition:f.definition,example:r[8]};});ch.contentVersion=5;});
})();
